global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: ['localhost:9090']

  - job_name: api-gateway
    static_configs:
    - targets: ['api-gateway:8000']

  - job_name: auth-service
    static_configs:
    - targets: ['auth-service:8000']

  - job_name: user-service
    static_configs:
    - targets: ['user-service:8000']

  - job_name: parking-slot-service
    static_configs:
    - targets: ['parking-slot-service:8000']

  - job_name: booking-service
    static_configs:
    - targets: ['booking-service:8000']

  - job_name: payment-service
    static_configs:
    - targets: ['payment-service:8000']

  - job_name: notification-service
    static_configs:
    - targets: ['notification-service:8000']

  - job_name: vehicle-tracking-service
    static_configs:
    - targets: ['vehicle-tracking-service:8000']

  - job_name: analytics-service
    static_configs:
    - targets: ['analytics-service:8000']

  - job_name: rabbitmq
    static_configs:
    - targets: ['rabbitmq:15692']

  - job_name: postgres
    static_configs:
    - targets: ['postgres-exporter:9187']

  - job_name: redis
    static_configs:
    - targets: ['redis-exporter:9121']